modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"
issueTrackerURL = "https://github.com/TheLMiffy1111/PackagedDraconic/issues"

[[mods]]
	modId="packageddraconic"
	version = "0@VERSION@"
	displayName="PackagedDraconic"
	description = "A PackagedAuto addon that adds Draconic Evolution fusion autocrafting."
	logoFile = "packageddraconic.logo.png"
	authors = "TheLMiffy1111"
	displayURL = "https://www.curseforge.com/minecraft/mc-mods/packageddraconic"

[[dependencies.packageddraconic]]
	modId = "forge"
	versionRange = "[40,)"
	mandatory = true

[[dependencies.packageddraconic]]
	modId = "packagedauto"
	versionRange = "[3.1.7,)"
	mandatory = true

[[dependencies.packageddraconic]]
	modId = "draconicevolution"
	versionRange = "[3,)"
	mandatory = true
